apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-express

spec:
  replicas: 4

  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp

    spec:
      containers:
        - name: myapp
          image: yashpatoliyakevit/demo-express:latest
          ports:
            - containerPort: 3000