version : '1.0'

services: 

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo-data:/data/db

  app:
    image: yashpatoliyakevit/practice-react:latest
    container_name: react-demo
    ports:
      - 5173:5173
    depends_on:
      - db
      
  